accounts/urls.py
from accounts.views import (AccountCreateView, AccountLoginView, 
                            AccountLogoutView, AccountPasswordView, 
                            AccountUpdateView)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', AccountCreateView.as_view(), name='register'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordView.as_view(), name='password'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),  

]

testify/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    

core/models.py
from django.db import models # noqa

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class AccountCreateForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']

accounts/views.py
# import datetime
from accounts.forms import (AccountCreateForm, 
                            AccountUpdateForm)

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic import CreateView 
from django.views.generic.edit import UpdateView


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')  # это редирект после завершения регистрации

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully created')
        return result


class AccountLoginView(LoginView):
    model = User
    template_name = 'login.html'
    success_url = reverse_lazy('link')

    # функция ниже переправляет на страницу откужа пришел пользователь
    # Если сработал LoginRequiredMixin

    def get_redirect_url(self):
        if self.request.GET.get('next'):  # это параметр Get запроса проверяет, есть ли 
            return self.request.GET.get('next')  # next в адресной строке
        return reverse('core:index')

    def form_valid(self, form):

        result = super().form_valid(form)
        messages.info(self.request, f'User {self.request.user} logged in!')

        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'
    
    def get(self, request, *args, **kwargs):
        result = super().get(request, *args, **kwargs)
        messages.info(self.request, f'User {self.request.user} has been logged out!')
        return result


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('link')  

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordView(LoginRequiredMixin, PasswordChangeView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'password.html'
    success_url = reverse_lazy('link')  

core/views.py
from django.shortcuts import render


def index(request):
    return render(
        request=request,
        template_name='index.html'
    )

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block header %}
<header>
    <p>Login</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
  
        <input class="btn btn-success" type="submit" value="Login">
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
    </form>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Logout</title>
{% endblock %}

{% block header %}
<header>
    <p>User is Logged Out</p>
</header>
{% endblock %}

{% block content %}
          
        <a class = "btn btn-sm " href="{% url 'accounts:login' %}">Login</a>
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
{% endblock %}

accounts/templates/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Change Password</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}
        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Edit user</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
         
        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.profile.image.url }}">
            </div>
    {#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
    {#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
    

        {% csrf_token %}
        {{user_form|crispy}}
        {{profile_form|crispy}}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
        <a class="btn btn-light" href="{% url 'accounts:password' %}">Change Password</a>
    </form>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Register new user</title>
{% endblock %}

{% block header %}
<header>
    <p>Login</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
  
        <input class="btn btn-success" type="submit" value="Register">
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
  <title>LMS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
</style>
</head>

<body>
    {% block title %}
    <title>Testify</title>
    {% endblock %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'core:index' %}">Testify</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">

         
          <a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a>
          <a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a>
          <a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a>
          

        </nav>
   
         {{ user  }}

         {% if user.is_authenticated %}
           
          <div class="img-circle.vert">
          <img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.profile.image.url }}">
          </div>

            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:profile' %}">Profile({{ user }})</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:logout' %}">Logout</a>
         {% else %}
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:login' %}">Sign In</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:register' %}">Register</a>
         {% endif %}

        
      </div>
    
    <div class="container">
    <div class="border border-primary rounded-pill text-center m-3">
      
    {% block header %}
    
    <header>
      {% include 'includes/messages.html' %}
      <strong><p>Welcome to Testify</p></strong>
    </header>
    {% endblock %}
    </div>   

    

    {% block content %}

    {% endblock %}

  </div>

</body>
</html>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/pagination.html
<nav aria-label="...">
    <ul class="pagination">
      <li class="page-item disabled">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
    {% endif %}
      </li>   
         

      {% for n in page_obj.paginator.page_range %}
         {% if page_obj.number == n %}
         <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
          </li>
         {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
         {% endif %}

      {% endfor %}

      {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
      </li>
    {% endif %}
    </ul>
  </nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Main Pages</title>
{% endblock %}

{% block content %}

<div class="container">
  <div class="card-deck mb-3 text-center">

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Notes</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a></h1>
        </div>
    </div>

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Index</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a></h1>
        </div>
    </div>


    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Index</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a></h1>
        </div>
    </div>

    </div>
  </div>
  

{% endblock %}